driver:	
  name: vagrant

platforms:
  - name: tas50/windows_2019	
    transport:	
      name: winrm	
    driver_config:	
      guest: :windows
      username: vagrant	
      password: vagrant	
      communicator: winrm

suites:
  - name: arthur
    driver: 
      vm_hostname: arthur
